### ISSUE TITLE
我进行搜索时报错了，搜索不了结果

### ISSUE THREAD

**Issue by qiushaocloud** [halo-dev/plugin-search-widget#29]
{
    "type": "about:blank",
    "title": "服务器内部错误",
    "status": 500,
    "detail": "服务器内部发生错误，请稍候再试。",
    "instance": "http://www.qiushaocloud.top:8091/apis/api.halo.run/v1alpha1/indices/post?keyword=Mac&highlightPreTag=%3Cmark%3E&highlightPostTag=%3C/mark%3E",
    "requestId": "37cfb519-70",
    "timestamp": "2024-04-21T12:34:10.962438010Z"
}

iushaocloud-halo2-server    | 2024-04-21T20:34:10.958+08:00  INFO 6 --- [tor-tcp-epoll-2] c.r.h.p.m.s.MeilisearchPostService       : search keyword: Mac
qiushaocloud-halo2-server    | 2024-04-21T20:34:10.962+08:00 ERROR 6 --- [tor-tcp-epoll-2] a.w.r.e.AbstractErrorWebExceptionHandler : [37cfb519-70]  500 Server Error for HTTP GET "/apis/api.halo.run/v1alpha1/indices/post?keyword=Mac&highlightPreTag=%3Cmark%3E&highlightPostTag=%3C/mark%3E"
qiushaocloud-halo2-server    | 
qiushaocloud-halo2-server    | com.meilisearch.sdk.exceptions.MeilisearchCommunicationException: java.net.UnknownHostException: meilisearch
qiushaocloud-halo2-server    |  at com.meilisearch.sdk.http.CustomOkHttpClient.execute(CustomOkHttpClient.java:45) ~[na:na]
qiushaocloud-halo2-server    |  Suppressed: reactor.core.publisher.FluxOnAssembly$OnAssemblyException: 
qiushaocloud-halo2-server    | Error has been observed at the following site(s):
qiushaocloud-halo2-server    |  *__checkpoint ⇢ run.halo.app.security.InitializeRedirectionWebFilter [DefaultWebFilterChain]
qiushaocloud-halo2-server    |  *__checkpoint ⇢ AuthorizationWebFilter [DefaultWebFilterChain]
qiushaocloud-halo2-server    |  *__checkpoint ⇢ ExceptionTranslationWebFilter [DefaultWebFilterChain]
qiushaocloud-halo2-server    |  *__checkpoint ⇢ LogoutWebFilter [DefaultWebFilterChain]
qiushaocloud-halo2-server    |  *__checkpoint ⇢ ServerRequestCacheWebFilter [DefaultWebFilterChain]
qiushaocloud-halo2-server    |  *__checkpoint ⇢ SecurityContextServerWebExchangeWebFilter [DefaultWebFilterChain]
qiushaocloud-halo2-server    |  *__checkpoint ⇢ LogoutPageGeneratingWebFilter [DefaultWebFilterChain]
qiushaocloud-halo2-server    |  *__checkpoint ⇢ AnonymousAuthenticationWebFilter [DefaultWebFilterChain]
qiushaocloud-halo2-server    |  *__checkpoint ⇢ SecurityWebFilterChainProxy [DefaultWebFilterChain]
qiushaocloud-halo2-server    |  *__checkpoint ⇢ TotpAuthenticationFilter [DefaultWebFilterChain]
qiushaocloud-halo2-server    |  *__checkpoint ⇢ AuthenticationWebFilter [DefaultWebFilterChain]
qiushaocloud-halo2-server    |  *__checkpoint ⇢ SecurityWebFilterChainProxy [DefaultWebFilterChain]
qiushaocloud-halo2-server    |  *__checkpoint ⇢ SecurityWebFilterChainProxy [DefaultWebFilterChain]
qiushaocloud-halo2-server    |  *__checkpoint ⇢ AuthenticationWebFilter [DefaultWebFilterChain]
qiushaocloud-halo2-server    |  *__checkpoint ⇢ AuthenticationWebFilter [DefaultWebFilterChain]
qiushaocloud-halo2-server    |  *__checkpoint ⇢ ReactorContextWebFilter [DefaultWebFilterChain]
qiushaocloud-halo2-server    |  *__checkpoint ⇢ CsrfWebFilter [DefaultWebFilterChain]
qiushaocloud-halo2-server    |  *__checkpoint ⇢ CorsWebFilter [DefaultWebFilterChain]
qiushaocloud-halo2-server    |  *__checkpoint ⇢ HttpHeaderWriterWebFilter [DefaultWebFilterChain]
qiushaocloud-halo2-server    |  *__checkpoint ⇢ ServerWebExchangeReactorContextWebFilter [DefaultWebFilterChain]
qiushaocloud-halo2-server    |  *__checkpoint ⇢ org.springframework.security.web.server.WebFilterChainProxy [DefaultWebFilterChain]
qiushaocloud-halo2-server    |  *__checkpoint ⇢ io.github.guqing.cloudinary.ImageOptimizerWebFilter [DefaultWebFilterChain]
qiushaocloud-halo2-server    |  *__checkpoint ⇢ run.halo.oauth.Oauth2Authenticator [DefaultWebFilterChain]
qiushaocloud-halo2-server    |  *__checkpoint ⇢ run.halo.oauth.Oauth2AuthorizationRequestRedirectWebFilter [DefaultWebFilterChain]
qiushaocloud-halo2-server    |  *__checkpoint ⇢ run.halo.app.webfilter.AdditionalWebFilterChainProxy [DefaultWebFilterChain]
qiushaocloud-halo2-server    |  *__checkpoint ⇢ HTTP GET "/apis/api.halo.run/v1alpha1/indices/post?keyword=Mac&highlightPreTag=%3Cmark%3E&highlightPostTag=%3C/mark%3E" [ExceptionHandlingWebHandler]
qiushaocloud-halo2-server    | Original Stack Trace:
qiushaocloud-halo2-server    |    at com.meilisearch.sdk.http.CustomOkHttpClient.execute(CustomOkHttpClient.java:45) ~[na:na]
qiushaocloud-halo2-server    |    at com.meilisearch.sdk.http.CustomOkHttpClient.post(CustomOkHttpClient.java:112) ~[na:na]
qiushaocloud-halo2-server    |    at com.meilisearch.sdk.HttpClient.post(HttpClient.java:95) ~[na:na]
qiushaocloud-halo2-server    |    at com.meilisearch.sdk.Search.rawSearch(Search.java:49) ~[na:na]
qiushaocloud-halo2-server    |    at com.meilisearch.sdk.Search.search(Search.java:76) ~[na:na]
qiushaocloud-halo2-server    |    at com.meilisearch.sdk.Index.search(Index.java:375) ~[na:na]
qiushaocloud-halo2-server    |    at com.rs.halo.plugin.meilisearch.service.MeilisearchPostService.search(MeilisearchPostService.java:51) ~[na:na]
qiushaocloud-halo2-server    |    at run.halo.app.search.post.PostSearchEndpoint.lambda$search$4(PostSearchEndpoint.java:57) ~[classes/:2.14.0]
qiushaocloud-halo2-server    |    at reactor.core.publisher.FluxMap$MapSubscriber.onNext(FluxMap.java:106) ~[reactor-core-3.6.4.jar:3.6.4]
qiushaocloud-halo2-server    |    at reactor.core.publisher.FluxSwitchIfEmpty$SwitchIfEmptySubscriber.onNext(FluxSwitchIfEmpty.java:74) ~[reactor-core-3.6.4.jar:3.6.4]
qiushaocloud-halo2-server    |    at reactor.core.publisher.FluxHandle$HandleSubscriber.onNext(FluxHandle.java:129) ~[reactor-core-3.6.4.jar:3.6.4]
qiushaocloud-halo2-server    |    at reactor.core.publisher.FluxSwitchIfEmpty$SwitchIfEmptySubscriber.onNext(FluxSwitchIfEmpty.java:74) ~[reactor-core-3.6.4.jar:3.6.4]
qiushaocloud-halo2-server    |    at reactor.core.publisher.Operators$ScalarSubscription.request(Operators.java:2571) ~[reactor-core-3.6.4.jar:3.6.4]
qiushaocloud-halo2-server    |    at reactor.core.publisher.Operators$MultiSubscriptionSubscriber.set(Operators.java:2367) ~[reactor-core-3.6.4.jar:3.6.4]
qiushaocloud-halo2-server    |    at reactor.core.publisher.Operators$MultiSubscriptionSubscriber.onSubscribe(Operators.java:2241) ~[reactor-core-3.6.4.jar:3.6.4]
qiushaocloud-halo2-server    |    at reactor.core.publisher.MonoJust.subscribe(MonoJust.java:55) ~[reactor-core-3.6.4.jar:3.6.4]
qiushaocloud-halo2-server    |    at reactor.core.publisher.Mono.subscribe(Mono.java:4568) ~[reactor-core-3.6.4.jar:3.6.4]
qiushaocloud-halo2-server    |    at reactor.core.publisher.FluxSwitchIfEmpty$SwitchIfEmptySubscriber.onComplete(FluxSwitchIfEmpty.java:82) ~[reactor-core-3.6.4.jar:3.6.4]

**Comment by qiushaocloud** [comment]
因为我用了 Meilisearch 插件的原因

**Comment by qiushaocloud** [comment]
已解决，跑 Meilisearch 起来配置好后，需要刷新下搜索引擎
